spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/kipService"
    username: postgres
    password: 253692472839
  #sql:
      #init:
        #mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
